---
title: "West Nile Virus Antibiotics - 16S - Single-End Protocol"
author: "Scott A. Handley & Barry Hykes, Jr"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: html_document
---

## References:
  ## http://f1000research.com/articles/5-1492/v1
  ## http://benjjneb.github.io/dada2/tutorial.html
  ## http://benjjneb.github.io/dada2/bigdata_paired.html

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=8,
                      fig.height=6,
                      fig.path="./figures/",
                      dev='pdf',
                      warning=FALSE,
                      message=FALSE)
```

```{r initiate-environment}
# Load libraries
library(ShortRead)
packageVersion("ShortRead")
library(dada2)
packageVersion("dada2")
library(ggplot2)
packageVersion("ggplot2")
library("msa")
packageVersion("msa")
library("phangorn")
packageVersion("phangorn")
library("phyloseq")
packageVersion("phyloseq")

```
Filter and trim the reads.

Settings need to be adjusted per run.

```{r filter, trim, and sample-inference for run }
# File parsing
pathF <- "/mnt/Endeavor_data2/bhykes/16s/Thackary_Aug_2017_revised/Run_368/forward" # CHANGE ME to the directory containing your demultiplexed forward-read fastq files
pathR <- "/mnt/Endeavor_data2/bhykes/16s/Thackary_Aug_2017_revised/Run_368/reverse" # CHANGE ME to the directory containing your demultiplexed forward-read fastq files
filtpath <- file.path(pathF, "filtered/single") # Filtered forward files go into the pathF/filtered/ subdirectory
filtpathR <- file.path(pathR, "filtered/single") # Filtered forward files go into the pathF/filtered/ subdirectory
fastqFs <- sort(list.files(pathF, pattern="fastq"))
fastqRs <- sort(list.files(pathR, pattern="fastq"))

# Plot forward and reverse read quality
p.qual.f <- plotQualityProfile(pathF[1], aggregate = TRUE) + ggtitle("Fwd")
p.qual.f
p.qual.R <- plotQualityProfile(pathR[1], aggregate = TRUE) + ggtitle("Rev")
p.qual.R

if(length(fastqFs) != length(fastqRs)) stop("Forward and reverse files do not match.")
filterAndTrim(fwd=file.path(pathF, fastq), filt=file.path(filtpath, fastq),
              trimLeft=10, truncLen=250, maxEE=2, truncQ=11, maxN=0, rm.phix=TRUE,
              compress=TRUE, verbose=TRUE, multithread=TRUE)


# Set paramaters
filts <- list.files(filtpath, pattern="fastq", full.names = TRUE)
sample.names <- sapply(strsplit(basename(filts), "_"), `[`, 1) # Assumes filename = samplename_XXX.fastq.gz
names(filts) <- sample.names

set.seed(100)

# Learn forward error rates
errF <- learnErrors(filts, nread=2e6, multithread=TRUE)
p.err.F <- plotErrors(errF, nominalQ = TRUE)
p.err.F

# Dereplicate, apply error rate to all sequences and merge
singles_ <- vector("list", length(sample.names))
names(singles_) <- sample.names
for(sam in sample.names) {
  cat("Processing:", sam, "\n")
    derepF <- derepFastq(filts[[sam]])
    singles_[[sam]] <- dada(derepF, err=errF, multithread=TRUE)
}
```


#Run 369
```{r examine-filter-trim}
# File parsing
pathF <- "/mnt/Endeavor_data2/bhykes/16s/Thackary_Aug_2017_revised/Run_369/forward" # CHANGE ME to the directory containing your demultiplexed forward-read fastq files
pathR <- "/mnt/Endeavor_data2/bhykes/16s/Thackary_Aug_2017_revised/Run_369/reverse" # CHANGE ME to the directory containing your demultiplexed forward-read fastq files
filtpathF <- file.path(pathF, "filtered/single") # Filtered forward files go into the pathF/filtered/ subdirectory
filtpathR <- file.path(pathR, "filtered/single") # Filtered forward files go into the pathF/filtered/ subdirectory
fastqFs <- sort(list.files(pathF, pattern="fastq"))
fastqRs <- sort(list.files(pathR, pattern="fastq"))

# Plot forward and reverse read quality
p.qual.f <- plotQualityProfile(pathF[1], aggregate = TRUE) + ggtitle("Fwd")
p.qual.f
p.qual.r <- plotQualityProfile(pathR[1], aggregate = TRUE) + ggtitle("Fwd")
p.qual.r

filterAndTrim(fwd=file.path(pathF, fastqFs), filt=file.path(filtpathF, fastqFs),
              trimLeft=10, truncLen=250, maxEE=2, truncQ=11, maxN=0, rm.phix=TRUE,
              compress=TRUE, verbose=TRUE, multithread=TRUE)


```
Error rate inference.

```{r sample-inference}
# Set paramaters
filtFs <- list.files(filtpathF, pattern="fastq", full.names = TRUE)
sample.names <- sapply(strsplit(basename(filtFs), "_"), `[`, 1) # Assumes filename = samplename_XXX.fastq.gz
names(filtFs) <- sample.names

set.seed(100)

# Learn forward error rates
errF <- learnErrors(filtFs, nread=2e6, multithread=TRUE)
p.err.F <- plotErrors(errF, nominalQ = TRUE)
p.err.F

# Dereplicate, apply error rate to all sequences and merge
singles <- vector("list", length(sample.names))
names(singles) <- sample.names
for(sam in sample.names) {
  cat("Processing:", sam, "\n")
    derepF <- derepFastq(filtFs[[sam]])
    singles[[sam]] <- dada(derepF, err=errF, multithread=TRUE)
}
rm(derepF);


save.image("/mnt/Endeavor_data2/bhykes/16s/Thackary_Aug_2017_revised/Thackary_Aug_2017_revised_16S_preprocessing_single.RData")
```
Construct sequence table and remove chimeras.

```{r seqtab-chimera-removal}
seqtabM368 <- makeSequenceTable(singles_)
seqtab.nochimM368 <- removeBimeraDenovo(seqtabM368, multithread=TRUE)
saveRDS(seqtab.nochimM368, "seqtab.nochimM368.rds")
seqtabM369 <- makeSequenceTable(singles)
seqtab.nochimM369 <- removeBimeraDenovo(seqtabM369, multithread=TRUE)
saveRDS(seqtab.nochimM369, "seqtab.nochimM369.rds")

save.image("/mnt/Endeavor_data2/bhykes/16s/Thackary_Aug_2017_revised/Thackary_Aug_2017_revised_16S_preprocessing_single.RData")
```
merge runs
```{r}
seqtab.nochim_allRuns <- mergeSequenceTables(seqtab.nochimM368,seqtab.nochimM369)
saveRDS(seqtab.nochim_allRuns, "seqtab.nochim_allRuns.rds")
save.image("/mnt/Endeavor_data2/bhykes/16s/Thackary_Aug_2017_revised/Thackary_Aug_2017_revised_16S_preprocessing_single.RData")
```
Assign taxonomy.
```{r assign-taxonomy}
# GreenGenes
taxa.gg <- assignTaxonomy(seqtab.nochim_allRuns, "/mnt/Endeavor_data1/databases/dada2_taxonomy/gg_13_8_train_set_97.fa.gz", multithread = TRUE)
unname(head(taxa.gg))
colnames(taxa.gg) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")

# RDP
taxa.rdp <- assignTaxonomy(seqtab.nochim_allRuns, "/mnt/Endeavor_data1/databases/dada2_taxonomy/rdp_train_set_16.fa.gz", multithread = TRUE)
unname(head(taxa.rdp))
colnames(taxa.rdp) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus")

# Silva
taxa.silva <- assignTaxonomy(seqtab.nochim_allRuns,  "/mnt/Endeavor_data1/databases/dada2_taxonomy/silva_nr_v128_train_set.fa.gz", multithread = TRUE)
unname(head(taxa.silva))
colnames(taxa.silva) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus")

# HitDB
taxa.hitdb <- assignTaxonomy(seqtab.nochim_allRuns, "/mnt/Endeavor_data1/databases/dada2_taxonomy/hitdb_v1.00.fa.gz", multithread = TRUE)

# Add species to RDP and Silva
#RDP
taxa.rdp.plus <- addSpecies(taxa.rdp, "/mnt/Endeavor_data1/databases/dada2_taxonomy/rdp_species_assignment_16.fa.gz")
unname(head(taxa.rdp.plus))
colnames(taxa.rdp.plus) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")

# SILVA
taxa.silva.plus <- addSpecies(taxa.silva, "/mnt/Endeavor_data1/databases/dada2_taxonomy/silva_species_assignment_v128.fa.gz")
unname(head(taxa.silva.plus))
colnames(taxa.silva.plus) <- c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")

save.image("/mnt/Endeavor_data2/bhykes/16s/Thackary_Aug_2017_revised/Thackary_Aug_2017_revised_16S_preprocessing_single.RData")
```
Construct the phylogenetic tree.

```{r construct-phylogeny}
seqs <- getSequences(seqtab.nochim_allRuns)

names(seqs) <- seqs # This propagates to the tip labels of the tree
mult <- msa(seqs, method="ClustalW", type="dna", order="input")

phang.align <- as.phyDat(mult, type="DNA", names=getSequence(seqtab.nochim_allRuns))

dm <- dist.ml(phang.align)
treeNJ <- NJ(dm) # Note, tip order != sequence order
fit = pml(treeNJ, data=phang.align)

fitGTR <- update(fit, k=4, inv=0.2)
fitGTR <- optim.pml(fitGTR, model="GTR", optInv=TRUE, optGamma=TRUE,
                       rearrangement = "stochastic", control = pml.control(trace = 0))
detach("package:phangorn", unload=TRUE)

save.image("/mnt/Endeavor_data2/bhykes/16s/Thackary_Aug_2017_revised/Thackary_Aug_2017_revised_16S_preprocessing_single.RData")
```

```{r create-phyloseq}
# Create PhyloSeq objects
# Greengenes
# Strip the r__ prefixes from taxon labels. This is only needed for the GreenGenes taxon annotations
taxa.gg.fixed <- gsub("k__", "", taxa.gg)
taxa.gg.fixed <- gsub("p__", "", taxa.gg.fixed)
taxa.gg.fixed <- gsub("c__", "", taxa.gg.fixed)
taxa.gg.fixed <- gsub("o__", "", taxa.gg.fixed)
taxa.gg.fixed <- gsub("f__", "", taxa.gg.fixed)
taxa.gg.fixed <- gsub("g__", "", taxa.gg.fixed)
taxa.gg.fixed <- gsub("s__", "", taxa.gg.fixed)

ps0.gg <- phyloseq(otu_table(seqtab.nochim_allRuns, taxa_are_rows = FALSE), tax_table(taxa.gg.fixed), phy_tree(fitGTR$tree))
ps0.gg

# RDP
ps0.rdp <- phyloseq(otu_table(seqtab.nochim_allRuns, taxa_are_rows = FALSE), tax_table(taxa.rdp.plus), phy_tree(fitGTR$tree))
ps0.rdp

# Silva
ps0.silva <- phyloseq(otu_table(seqtab.nochim_allRuns, taxa_are_rows = FALSE), tax_table(taxa.silva.plus), phy_tree(fitGTR$tree))
ps0.silva

# HitDb
ps0.hitdb <- phyloseq(otu_table(seqtab.nochim_allRuns, taxa_are_rows = FALSE), tax_table(taxa.hitdb), phy_tree(fitGTR$tree))
ps0.hitdb

# Sanity checks
get_taxa_unique(ps0.gg, "Phylum")
get_taxa_unique(ps0.rdp, "Phylum")
get_taxa_unique(ps0.silva, "Phylum")
get_taxa_unique(ps0.hitdb, "Phylum")

# Save RDS files for downstream analysis
saveRDS(ps0.gg, file = "/mnt/Endeavor_data2/bhykes/16s/Thackary_Aug_2017_revised/ps0.Thackary_Aug_2017_revised.gg_single.RDS")
saveRDS(ps0.rdp, file = "/mnt/Endeavor_data2/bhykes/16s/Thackary_Aug_2017_revised/ps0.Thackary_Aug_2017_revised.rdp_single.RDS")
saveRDS(ps0.silva, file = "/mnt/Endeavor_data2/bhykes/16s/Thackary_Aug_2017_revised/ps0.Thackary_Aug_2017_revised.silva_single.RDS")
saveRDS(ps0.hitdb, file = "/mnt/Endeavor_data2/bhykes/16s/Thackary_Aug_2017_revised/ps0.Thackary_Aug_2017_revised.hitdb_single.RDS")

save.image("/mnt/Endeavor_data2/bhykes/16s/Thackary_Aug_2017_revised/Thackary_Aug_2017_revised_16S_preprocessing_single.RData")

```


